services:
  vk-parser:
    build:
      context: .
      dockerfile: Dockerfile.vk-parser
    volumes:
      - ./parsers:/app/parsers
      - ./temp_vk_config.json:/app/temp_vk_config.json
      - ./vk_playlists.db:/app/vk_playlists.db
    environment:
      - BRIGHT_DATA_RESIDENTIAL_USERNAME=${BRIGHT_DATA_RESIDENTIAL_USERNAME:-HYRrWAXb}
      - BRIGHT_DATA_RESIDENTIAL_PASSWORD=${BRIGHT_DATA_RESIDENTIAL_PASSWORD:-Dfi5FeEC}
      - PROXY_HOST=${PROXY_HOST:-94.154.188.161}
      - PROXY_PORT=${PROXY_PORT:-63194}
    shm_size: '2gb'

